---
title: "p8105_hw3_cw3747"
author: "chuhan wang_cw3747"
date: "2025-10-05"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(patchwork)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem1
### 1.1
```{r}
library(p8105.datasets)
data("instacart")
```

```{r}
instacart <- instacart |>
  janitor::clean_names() 

n_aisles <- n_distinct(instacart$aisle)    ## calculate aisles

aisle_counts <- instacart |>
  count(aisle, name = "n_items") |>       ## count the number of each item
  arrange(desc(n_items))   ## top aisles

n_aisles
head(aisle_counts, 10)
```
There are **`r n_aisles`** aisles in the instacart dataset, and the most orderd items are **`r aisle_counts$aisle[1:3]`**.

### 1.2
```{r}
aisle_counts |>
  filter(n_items > 10000) |>
  mutate(aisle = fct_reorder(aisle, n_items)) |>
  ggplot(aes(x = aisle, y = n_items)) +
  geom_col() +
  coord_flip() +           ## for easy reading
  labs(x = "Aisle", y = "Items ordered", title = ">10k items per aisle") +
  theme_minimal()
```

### 1.3
```{r}
sel_aisles <- c("baking ingredients", "dog food care", "packaged vegetables fruits")

popular_items <- instacart |>
  filter(aisle %in% sel_aisles) |>               ## keep the three aisles
  select(aisle, product_name) |>                  
  count(aisle, product_name, name = "n_orders") |>  ## keep product name and number
  group_by(aisle) |>
  slice_max(n_orders, n = 3, with_ties = FALSE) |>
  arrange(aisle, desc(n_orders)) |>
  ungroup()

popular_items
```

## 1.4
```{r}
library(gt)
products <- c("Pink Lady Apples", "Coffee Ice Cream")

weekday_levels <- c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")    ## to make readable

mean_hour <- instacart |>
  filter(product_name %in% products) |>
  mutate(dow = factor(weekday_levels[order_dow + 1],
                    levels = weekday_levels)) |>
  group_by(product_name, dow) |>
  summarize(mean_hour = mean(order_hour_of_day, na.rm = TRUE), .groups = "drop") |>
  mutate(mean_hour = round(mean_hour, 1)) |>
  pivot_wider(names_from = dow, values_from = mean_hour) |>
  arrange(match(product_name, products))

mean_hour |>
  gt() |>
  tab_header(title = "Mean order time by weekday (hours, 24h)") |>
  cols_label(product_name = "Product")
```

